### PR TITLE
PHP 7 adjustments

### PR DESCRIPTION
**Pull request by kaplanlior**
PHP 7 adjustments for PDO_IBM 1.3.4 by Zend.

### CODE REVIEW

**Comment by kaplanlior** [comment]
@alanseiden - FYI

**Comment by NattyNarwhal** [comment]
I was just made aware of the PR recently. It seems like a lot of the changes in it got replicated into the mainline version after all, but there might be some that got missed. I'll keep my eye on this and see what I can cherry pick out.

**Comment by NattyNarwhal** [comment]
I took a look at this PR again (sorry after all the delay) after being prompted and I think we've actually merged most of it in save for some zend_ulong/zend_long conversions and lastInsertID; since we made most of the size_t conversions. I'll probably commit them as separate commits and mark you as author.

**Comment by NattyNarwhal** [comment]
I've just pushed the changes from this to here (with some modifications of my own). Only one I wasn't sure of was the change in the describer to use `col_res->namelen` instead of `strlen`. Please reopen this if I goofed.

**Comment by kadler** [comment]
I suspect not using `strlen` is wrong. Unless you're **absolutely** sure the fetch did not overflow, the length returned in the indicator will be the length _needed_, not the actual length. The value must always be null-terminated, so using `strlen` will give the correct result regardless of overflow or not.

**Pull request closed without merging**
